# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "7180d3a7a2f9a3b1cde9c734b64a23ce"
name = "consumer-app"
handle = "consumer-app"
application_url = "https://units-der-baths-handed.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "athul-storer.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_product_listings,read_products,write_products"

[auth]
redirect_urls = [
  "https://units-der-baths-handed.trycloudflare.com/auth/callback",
  "https://units-der-baths-handed.trycloudflare.com/auth/shopify/callback",
  "https://units-der-baths-handed.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
